# Rate
GOOD_SCORE = "Good"
MEDIUM_SCORE = "Medium"
BAD_SCORE = "Bad"
VERYBAD_SCORE = "Very Bad"

# Data Mode
START_MODE = "START"
END_MODE = "END"

# Indicator Mode 
EFFECTIVENESS_MODE = 1
EFFCIENCY_MODE = 2
PRODUCTITIVTY_MODE = 3

# Date Mode
DATE_MODE = 1
QUARTER_MODE = 2

# Model Type
ARIMA_MODEL = 1
EXPONENTIAL_SMOOTHING_MODEL = 2